In [1]:
import pandas as pd
import numpy as np

In [2]:
sales_food= pd.read_csv("DATA/us_monthly_retail_sales_wrangled.csv")

In [3]:
sales_food.head(20)

,Unnamed: 0,month,year,naics_Code,kind_of_business,industry,sales
0,0,1,2022,441,Motor vehicle and parts dealers,Automotive,113548.0
1,1,1,2022,"44,114,412",Automobile and other motor vehicle dealers,Automotive,104500.0
2,2,1,2022,4411,Automobile dealers,Automotive,96689.0
3,3,1,2022,44111,New car dealers,Automotive,84442.0
4,4,1,2022,44112,Used car dealers,Automotive,12247.0
5,5,1,2022,4413,"Automotive parts, acc., and tire stores",Automotive,9047.0
6,6,1,2022,"442,443","Furniture, home furn, electronics, and applian...",Home Goods & Electronics,17141.0
7,7,1,2022,442,Furniture and home furnishings stores,Home Goods & Electronics,10423.0
8,8,1,2022,4421,Furniture stores,Home Goods & Electronics,5549.0
9,9,1,2022,4422,Home furnishings stores,Home Goods & Electronics,NaN
10,10,1,2022,44221,Floor covering stores,Home Goods & Electronics,NaN
11,11,1,2022,442299,All other home furnishings stores,Home Goods & Electronics,NaN
12,12,1,2022,443,Electronics and appliance stores,Home Goods & Electronics,6718.0
13,13,1,2022,443141,Household appliance stores,Home Goods & Electronics,1547.0
14,14,1,2022,443142,Electronics stores,Home Goods & Electronics,5171.0
15,15,1,2022,444,Building mat. and garden equip. and supplies d...,Home Goods & Building Supplies,33771.0
16,16,1,2022,4441,Building mat. and supplies dealers,Home Goods & Building Supplies,29770.0
17,17,1,2022,44412,Paint and wallpaper stores,Home Goods & Building Supplies,1051.0
18,18,1,2022,44413,Hardware stores,Home Goods & Building Supplies,2728.0
19,19,1,2022,445,Food and beverage stores,Food & Beverage,74984.0

In [4]:
print("shape", np.shape(sales_food))

shape (9048, 7)

In [5]:
print("\nColumns:")
print(sales_food.columns.tolist())

Columns:
['Unnamed: 0', 'month', 'year', 'naics_Code', 'kind_of_business', 'industry', 'sales']

In [6]:
print("\nInfo:")
sales_food.info()

Info:
<class 'pandas.DataFrame'>
RangeIndex: 9048 entries, 0 to 9047
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        9048 non-null   int64
 1   month             9048 non-null   int64
 2   year              9048 non-null   int64
 3   naics_Code        9048 non-null   str
 4   kind_of_business  9048 non-null   str
 5   industry          9048 non-null   str
 6   sales             8787 non-null   float64
dtypes: float64(1), int64(3), str(3)
memory usage: 494.9 KB

In [7]:
print("\nduplicates Values:")
print(sales_food.duplicated().sum())

duplicates Values:
0

In [8]:
print("\nMissing Values:")
print(sales_food.isna().sum().sort_values(ascending=False))

Missing Values:
sales               261
month                 0
Unnamed: 0            0
year                  0
naics_Code            0
kind_of_business      0
industry              0
dtype: int64

In [9]:
sales_food["sales"] = sales_food["sales"].fillna(sales_food["sales"].mean())

In [10]:
sales_food["sales"] = sales_food["sales"].round(2)

In [11]:
sales_food.head(20)

,Unnamed: 0,month,year,naics_Code,kind_of_business,industry,sales
0,0,1,2022,441,Motor vehicle and parts dealers,Automotive,113548.00
1,1,1,2022,"44,114,412",Automobile and other motor vehicle dealers,Automotive,104500.00
2,2,1,2022,4411,Automobile dealers,Automotive,96689.00
3,3,1,2022,44111,New car dealers,Automotive,84442.00
4,4,1,2022,44112,Used car dealers,Automotive,12247.00
5,5,1,2022,4413,"Automotive parts, acc., and tire stores",Automotive,9047.00
6,6,1,2022,"442,443","Furniture, home furn, electronics, and applian...",Home Goods & Electronics,17141.00
7,7,1,2022,442,Furniture and home furnishings stores,Home Goods & Electronics,10423.00
8,8,1,2022,4421,Furniture stores,Home Goods & Electronics,5549.00
9,9,1,2022,4422,Home furnishings stores,Home Goods & Electronics,21850.77
10,10,1,2022,44221,Floor covering stores,Home Goods & Electronics,21850.77
11,11,1,2022,442299,All other home furnishings stores,Home Goods & Electronics,21850.77
12,12,1,2022,443,Electronics and appliance stores,Home Goods & Electronics,6718.00
13,13,1,2022,443141,Household appliance stores,Home Goods & Electronics,1547.00
14,14,1,2022,443142,Electronics stores,Home Goods & Electronics,5171.00
15,15,1,2022,444,Building mat. and garden equip. and supplies d...,Home Goods & Building Supplies,33771.00
16,16,1,2022,4441,Building mat. and supplies dealers,Home Goods & Building Supplies,29770.00
17,17,1,2022,44412,Paint and wallpaper stores,Home Goods & Building Supplies,1051.00
18,18,1,2022,44413,Hardware stores,Home Goods & Building Supplies,2728.00
19,19,1,2022,445,Food and beverage stores,Food & Beverage,74984.00

In [12]:
sales_food["month"] = pd.to_datetime(sales_food["month"], format="%m").dt.strftime("%B")

In [13]:
sales_food.head(20)

,Unnamed: 0,month,year,naics_Code,kind_of_business,industry,sales
0,0,January,2022,441,Motor vehicle and parts dealers,Automotive,113548.00
1,1,January,2022,"44,114,412",Automobile and other motor vehicle dealers,Automotive,104500.00
2,2,January,2022,4411,Automobile dealers,Automotive,96689.00
3,3,January,2022,44111,New car dealers,Automotive,84442.00
4,4,January,2022,44112,Used car dealers,Automotive,12247.00
5,5,January,2022,4413,"Automotive parts, acc., and tire stores",Automotive,9047.00
6,6,January,2022,"442,443","Furniture, home furn, electronics, and applian...",Home Goods & Electronics,17141.00
7,7,January,2022,442,Furniture and home furnishings stores,Home Goods & Electronics,10423.00
8,8,January,2022,4421,Furniture stores,Home Goods & Electronics,5549.00
9,9,January,2022,4422,Home furnishings stores,Home Goods & Electronics,21850.77
10,10,January,2022,44221,Floor covering stores,Home Goods & Electronics,21850.77
11,11,January,2022,442299,All other home furnishings stores,Home Goods & Electronics,21850.77
12,12,January,2022,443,Electronics and appliance stores,Home Goods & Electronics,6718.00
13,13,January,2022,443141,Household appliance stores,Home Goods & Electronics,1547.00
14,14,January,2022,443142,Electronics stores,Home Goods & Electronics,5171.00
15,15,January,2022,444,Building mat. and garden equip. and supplies d...,Home Goods & Building Supplies,33771.00
16,16,January,2022,4441,Building mat. and supplies dealers,Home Goods & Building Supplies,29770.00
17,17,January,2022,44412,Paint and wallpaper stores,Home Goods & Building Supplies,1051.00
18,18,January,2022,44413,Hardware stores,Home Goods & Building Supplies,2728.00
19,19,January,2022,445,Food and beverage stores,Food & Beverage,74984.00

In [14]:
print(sales_food["naics_Code"].unique())

<StringArray>
[                   '441',             '44,114,412',                   '4411',
                  '44111',                  '44112',                   '4413',
                '442,443',                    '442',                   '4421',
                   '4422',                  '44221',                 '442299',
                    '443',                 '443141',                 '443142',
                    '444',                   '4441',                  '44412',
                  '44413',                    '445',                   '4451',
                  '44511',                   '4453',                    '446',
                  '44611',                    '447',                    '448',
                   '4481',                  '44811',                  '44812',
                  '44814',                  '44819',                   '4482',
                  '44831',                    '451',                  '45111',
                  '45112',                 '451211',                    '452',
                   '4521',                 '452111',                 '452112',
                   '4529',                  '45291',                  '45299',
                    '453',                   '4532',                  '45321',
                  '45322',                  '45330',                    '454',
                   '4541',                  '45431',                    '722',
                   '7224',                   '7225',                 '722511',
 '722513, 722514, 722515']
Length: 58, dtype: str

In [15]:
naics_map = {
    '441': 'Motor Vehicle & Parts Dealers',
    '44,114,412': 'Motor Vehicle & Parts Dealers (Combined)',
    '4411': 'Automobile Dealers',
    '44111': 'New Car Dealers',
    '44112': 'Used Car Dealers',
    '4413': 'Auto Parts, Accessories & Tire Stores',
    '442,443': 'Furniture & Electronics Stores (Combined)',
    '442': 'Furniture & Home Furnishings Stores',
    '4421': 'Furniture Stores',
    '4422': 'Home Furnishings Stores',
    '44221': 'Floor Covering Stores',
    '442299': 'All Other Home Furnishings Stores',
    '443': 'Electronics & Appliance Stores',
    '443141': 'Household Appliance Stores',
    '443142': 'Electronics Stores',
    '444': 'Building Material & Garden Supply Stores',
    '4441': 'Building Material & Supplies Dealers',
    '44412': 'Paint & Wallpaper Stores',
    '44413': 'Hardware Stores',
    '445': 'Food & Beverage Stores',
    '4451': 'Grocery Stores',
    '44511': 'Supermarkets & Grocery Stores',
    '4453': 'Beer, Wine & Liquor Stores',
    '446': 'Health & Personal Care Stores',
    '44611': 'Pharmacies & Drug Stores',
    '447': 'Gasoline Stations',
    '448': 'Clothing & Clothing Accessories Stores',
    '4481': 'Clothing Stores',
    '44811': 'Men\'s Clothing Stores',
    '44812': 'Women\'s Clothing Stores',
    '44814': 'Family Clothing Stores',
    '44819': 'Other Clothing Stores',
    '4482': 'Shoe Stores',
    '44831': 'Jewelry Stores',
    '451': 'Sporting Goods, Hobby, Book & Music Stores',
    '45111': 'Sporting Goods Stores',
    '45112': 'Hobby, Toy & Game Stores',
    '451211': 'Book Stores',
    '452': 'General Merchandise Stores',
    '4521': 'Department Stores',
    '452111': 'Department Stores (Except Discount)',
    '452112': 'Discount Department Stores',
    '4529': 'Other General Merchandise Stores',
    '45291': 'Warehouse Clubs & Supercenters',
    '45299': 'All Other General Merchandise Stores',
    '453': 'Miscellaneous Store Retailers',
    '4532': 'Office Supplies, Stationery & Gift Stores',
    '45321': 'Office Supplies & Stationery Stores',
    '45322': 'Gift, Novelty & Souvenir Stores',
    '45330': 'Used Merchandise Stores',
    '454': 'Nonstore Retailers',
    '4541': 'Electronic Shopping & Mail-Order Houses',
    '45431': 'Fuel Dealers',
    '722': 'Food Services & Drinking Places',
    '7224': 'Drinking Places (Alcoholic Beverages)',
    '7225': 'Restaurants & Other Eating Places',
    '722511': 'Full-Service Restaurants',
    '722513, 722514, 722515': 'Limited-Service & Snack & Beverage Places',
}

sales_food["naics_Code"] = sales_food["naics_Code"].str.strip().map(naics_map)
print(sales_food["naics_Code"].unique())

<StringArray>
[             'Motor Vehicle & Parts Dealers',
   'Motor Vehicle & Parts Dealers (Combined)',
                         'Automobile Dealers',
                            'New Car Dealers',
                           'Used Car Dealers',
      'Auto Parts, Accessories & Tire Stores',
  'Furniture & Electronics Stores (Combined)',
        'Furniture & Home Furnishings Stores',
                           'Furniture Stores',
                    'Home Furnishings Stores',
                      'Floor Covering Stores',
          'All Other Home Furnishings Stores',
             'Electronics & Appliance Stores',
                 'Household Appliance Stores',
                         'Electronics Stores',
   'Building Material & Garden Supply Stores',
       'Building Material & Supplies Dealers',
                   'Paint & Wallpaper Stores',
                            'Hardware Stores',
                     'Food & Beverage Stores',
                             'Grocery Stores',
              'Supermarkets & Grocery Stores',
                 'Beer, Wine & Liquor Stores',
              'Health & Personal Care Stores',
                   'Pharmacies & Drug Stores',
                          'Gasoline Stations',
     'Clothing & Clothing Accessories Stores',
                            'Clothing Stores',
                      'Men's Clothing Stores',
                    'Women's Clothing Stores',
                     'Family Clothing Stores',
                      'Other Clothing Stores',
                                'Shoe Stores',
                             'Jewelry Stores',
 'Sporting Goods, Hobby, Book & Music Stores',
                      'Sporting Goods Stores',
                   'Hobby, Toy & Game Stores',
                                'Book Stores',
                 'General Merchandise Stores',
                          'Department Stores',
        'Department Stores (Except Discount)',
                 'Discount Department Stores',
           'Other General Merchandise Stores',
             'Warehouse Clubs & Supercenters',
       'All Other General Merchandise Stores',
              'Miscellaneous Store Retailers',
  'Office Supplies, Stationery & Gift Stores',
        'Office Supplies & Stationery Stores',
            'Gift, Novelty & Souvenir Stores',
                    'Used Merchandise Stores',
                         'Nonstore Retailers',
    'Electronic Shopping & Mail-Order Houses',
                               'Fuel Dealers',
            'Food Services & Drinking Places',
      'Drinking Places (Alcoholic Beverages)',
          'Restaurants & Other Eating Places',
                   'Full-Service Restaurants',
  'Limited-Service & Snack & Beverage Places']
Length: 58, dtype: str

In [16]:
print(sales_food["naics_Code"].unique())

<StringArray>
[             'Motor Vehicle & Parts Dealers',
   'Motor Vehicle & Parts Dealers (Combined)',
                         'Automobile Dealers',
                            'New Car Dealers',
                           'Used Car Dealers',
      'Auto Parts, Accessories & Tire Stores',
  'Furniture & Electronics Stores (Combined)',
        'Furniture & Home Furnishings Stores',
                           'Furniture Stores',
                    'Home Furnishings Stores',
                      'Floor Covering Stores',
          'All Other Home Furnishings Stores',
             'Electronics & Appliance Stores',
                 'Household Appliance Stores',
                         'Electronics Stores',
   'Building Material & Garden Supply Stores',
       'Building Material & Supplies Dealers',
                   'Paint & Wallpaper Stores',
                            'Hardware Stores',
                     'Food & Beverage Stores',
                             'Grocery Stores',
              'Supermarkets & Grocery Stores',
                 'Beer, Wine & Liquor Stores',
              'Health & Personal Care Stores',
                   'Pharmacies & Drug Stores',
                          'Gasoline Stations',
     'Clothing & Clothing Accessories Stores',
                            'Clothing Stores',
                      'Men's Clothing Stores',
                    'Women's Clothing Stores',
                     'Family Clothing Stores',
                      'Other Clothing Stores',
                                'Shoe Stores',
                             'Jewelry Stores',
 'Sporting Goods, Hobby, Book & Music Stores',
                      'Sporting Goods Stores',
                   'Hobby, Toy & Game Stores',
                                'Book Stores',
                 'General Merchandise Stores',
                          'Department Stores',
        'Department Stores (Except Discount)',
                 'Discount Department Stores',
           'Other General Merchandise Stores',
             'Warehouse Clubs & Supercenters',
       'All Other General Merchandise Stores',
              'Miscellaneous Store Retailers',
  'Office Supplies, Stationery & Gift Stores',
        'Office Supplies & Stationery Stores',
            'Gift, Novelty & Souvenir Stores',
                    'Used Merchandise Stores',
                         'Nonstore Retailers',
    'Electronic Shopping & Mail-Order Houses',
                               'Fuel Dealers',
            'Food Services & Drinking Places',
      'Drinking Places (Alcoholic Beverages)',
          'Restaurants & Other Eating Places',
                   'Full-Service Restaurants',
  'Limited-Service & Snack & Beverage Places']
Length: 58, dtype: str

In [17]:
sales_food.head(20)

,Unnamed: 0,month,year,naics_Code,kind_of_business,industry,sales
0,0,January,2022,Motor Vehicle & Parts Dealers,Motor vehicle and parts dealers,Automotive,113548.00
1,1,January,2022,Motor Vehicle & Parts Dealers (Combined),Automobile and other motor vehicle dealers,Automotive,104500.00
2,2,January,2022,Automobile Dealers,Automobile dealers,Automotive,96689.00
3,3,January,2022,New Car Dealers,New car dealers,Automotive,84442.00
4,4,January,2022,Used Car Dealers,Used car dealers,Automotive,12247.00
5,5,January,2022,"Auto Parts, Accessories & Tire Stores","Automotive parts, acc., and tire stores",Automotive,9047.00
6,6,January,2022,Furniture & Electronics Stores (Combined),"Furniture, home furn, electronics, and applian...",Home Goods & Electronics,17141.00
7,7,January,2022,Furniture & Home Furnishings Stores,Furniture and home furnishings stores,Home Goods & Electronics,10423.00
8,8,January,2022,Furniture Stores,Furniture stores,Home Goods & Electronics,5549.00
9,9,January,2022,Home Furnishings Stores,Home furnishings stores,Home Goods & Electronics,21850.77
10,10,January,2022,Floor Covering Stores,Floor covering stores,Home Goods & Electronics,21850.77
11,11,January,2022,All Other Home Furnishings Stores,All other home furnishings stores,Home Goods & Electronics,21850.77
12,12,January,2022,Electronics & Appliance Stores,Electronics and appliance stores,Home Goods & Electronics,6718.00
13,13,January,2022,Household Appliance Stores,Household appliance stores,Home Goods & Electronics,1547.00
14,14,January,2022,Electronics Stores,Electronics stores,Home Goods & Electronics,5171.00
15,15,January,2022,Building Material & Garden Supply Stores,Building mat. and garden equip. and supplies d...,Home Goods & Building Supplies,33771.00
16,16,January,2022,Building Material & Supplies Dealers,Building mat. and supplies dealers,Home Goods & Building Supplies,29770.00
17,17,January,2022,Paint & Wallpaper Stores,Paint and wallpaper stores,Home Goods & Building Supplies,1051.00
18,18,January,2022,Hardware Stores,Hardware stores,Home Goods & Building Supplies,2728.00
19,19,January,2022,Food & Beverage Stores,Food and beverage stores,Food & Beverage,74984.00

# data overview

In [18]:

# ============================================
# KPI CARDS
# ==========================================

In [19]:
total_sales = sales_food["sales"].sum()
best_month = sales_food.groupby("month")["sales"].sum().idxmax()
top_industry = sales_food.groupby("industry")["sales"].sum().idxmax()
avg_sales = sales_food["sales"].mean()

print("=" * 40)
print(f"💰 Total Sales:     ${total_sales:,.2f}")
print(f"📅 Best Month:      {best_month}")
print(f"🏆 Top Industry:    {top_industry}")
print(f"📊 Average Sales:   ${avg_sales:,.2f}")
print("=" * 40)

========================================
💰 Total Sales:     $197,705,776.97
📅 Best Month:      December
🏆 Top Industry:    Automotive
📊 Average Sales:   $21,850.77
========================================

In [20]:
# ============================================
# SALES SHARE BY INDUSTRY (% of Total)
# ============================================

In [21]:
industry_share = sales_food.groupby("industry")["sales"].sum()
industry_share = (industry_share / industry_share.sum() * 100).round(2).sort_values(ascending=False)
industry_share.name = "sales_share_%"
print(industry_share)

industry
Automotive                        27.23
Food & Beverage                   16.58
Restaurants & Bars                12.58
General Merchandise               10.64
Home Goods & Electronics           9.28
Miscellaneous                      5.25
Fashion & Accessories              4.83
Home Goods & Building Supplies     4.59
Health & Personal Care             3.85
Fuel & Gasoline                    3.68
Sports & Recreation                1.07
Office Supplies & Gifts            0.41
Name: sales_share_%, dtype: float64

In [22]:
top10 = sales_food.groupby("kind_of_business")["sales"].sum().nlargest(10).reset_index()
print(top10)

                                    kind_of_business       sales
0                    Motor vehicle and parts dealers  14531121.0
1         Automobile and other motor vehicle dealers  13310756.0
2                                 Automobile dealers  12389347.0
3                                    New car dealers  10980583.0
4                           Food and beverage stores   9451004.0
5                         General merchandise stores   9038491.0
6                  Food services and drinking places   8635492.0
7                                 Nonstore retailers   8511856.0
8                                     Grocery stores   8463197.0
9  Supermarkets and other grocery (except conveni...   8092220.0

In [23]:
# ============================================
# SALES BY MONTH
# ============================================
month_order = ["January","February","March","April","May","June",
               "July","August","September","October","November","December"]
monthly_sales = (sales_food.groupby("month")["sales"].sum()
                 .reindex([m for m in month_order if m in sales_food["month"].values])
                 .reset_index())
print(monthly_sales)

        month        sales
0     January  14554513.09
1    February  14485459.86
2       March  16620169.17
3       April  15966589.17
4         May  16997337.94
5        June  16609989.94
6        July  16767182.94
7      August  17093027.94
8   September  16037848.94
9     October  16632662.25
10   November  16962497.25
11   December  18978498.48

In [24]:
# ============================================
# FOOD vs RETAIL vs AUTOMOTIVE
# ============================================
sales_food["category"] = sales_food["industry"].apply(
    lambda x: "Food" if "Food" in x or "Restaurant" in x
    else "Automotive" if "Automotive" in x
    else "Retail"
)
category_sales = sales_food.groupby("category")["sales"].sum().reset_index()
print(category_sales)

     category        sales
0  Automotive  53840935.00
1        Food  57652396.61
2      Retail  86212445.36

In [25]:
# ============================================
# HEATMAP DATA — MONTH vs INDUSTRY
# ============================================
heatmap_data = sales_food.pivot_table(
    values="sales", index="industry", columns="month", aggfunc="sum"
).round(2)
print(heatmap_data)

month                                April      August    December  \
industry
Automotive                      4471542.00  4822818.00  4614576.00
Fashion & Accessories            717382.31   829908.08  1202977.08
Food & Beverage                 2639095.00  2773945.00  3047368.00
Fuel & Gasoline                  598225.00   637891.00   592709.00
General Merchandise             1646201.00  1763321.00  2397021.00
Health & Personal Care           620379.00   638462.00   710582.00
Home Goods & Building Supplies   821716.00   789035.00   703640.00
Home Goods & Electronics        1399797.70  1537301.70  2028320.24
Miscellaneous                    810350.00   858254.00  1151444.00
Office Supplies & Gifts           58410.00    77202.00    88116.00
Restaurants & Bars              2028506.16  2166901.16  2163522.16
Sports & Recreation              154985.00   197989.00   278223.00

month                             February     January        July  \
industry
Automotive                      4037466.00  3867979.00  4696992.00
Fashion & Accessories            640647.54   571327.54   781147.08
Food & Beverage                 2447797.00  2603589.00  2787292.00
Fuel & Gasoline                  540344.00   562150.00   641454.00
General Merchandise             1513817.00  1499961.00  1706786.00
Health & Personal Care           589183.00   621954.00   624555.00
Home Goods & Building Supplies   575609.00   589646.00   809875.00
Home Goods & Electronics        1325620.93  1363317.93  1486597.70
Miscellaneous                    745395.00   780163.00   827397.00
Office Supplies & Gifts           57862.00    59290.00    67578.00
Restaurants & Bars              1874674.39  1881766.62  2166734.16
Sports & Recreation              137044.00   153369.00   170775.00

month                                 June       March         May  \
industry
Automotive                      4637376.00  4759220.00  4763342.00
Fashion & Accessories            765258.08   756845.31   795192.08
Food & Beverage                 2720797.00  2742088.00  2799623.00
Fuel & Gasoline                  632389.00   611964.00   637026.00
General Merchandise             1713206.00  1727210.00  1764913.00
Health & Personal Care           624898.00   650365.00   634257.00
Home Goods & Building Supplies   859096.00   745738.00   902307.00
Home Goods & Electronics        1466257.70  1469632.70  1471855.70
Miscellaneous                    827938.00   826692.00   850405.00
Office Supplies & Gifts           62996.00    61518.00    64322.00
Restaurants & Bars              2124304.16  2102825.16  2148378.16
Sports & Recreation              175474.00   166071.00   165717.00

month                             November     October   September
industry
Automotive                      4268662.00  4470684.00  4430278.00
Fashion & Accessories            920576.85   811783.85   746514.08
Food & Beverage                 2810868.00  2751956.00  2654253.00
Fuel & Gasoline                  590186.00   629626.00   605948.00
General Merchandise             1952466.00  1729786.00  1622846.00
Health & Personal Care           629287.00   649689.00   622969.00
Home Goods & Building Supplies   740986.00   780991.00   754760.00
Home Goods & Electronics        1772503.24  1552984.24  1481973.70
Miscellaneous                    987668.00   884878.00   826453.00
Office Supplies & Gifts           65518.00    79108.00    69054.00
Restaurants & Bars              2030896.16  2130602.16  2054615.16
Sports & Recreation              192880.00   160574.00   168185.00

In [26]:

best_months = sales_food.groupby("month")["sales"].sum().sort_values(ascending=False).reset_index()

best_industry_per_month = (
    sales_food.groupby(["month", "industry"])["sales"].sum()
    .reset_index().sort_values(["month", "sales"], ascending=[True, False])
    .groupby("month").first().reset_index()
)

best_business_per_industry = (
    sales_food.groupby(["industry", "kind_of_business"])["sales"].sum()
    .reset_index().sort_values(["industry", "sales"], ascending=[True, False])
    .groupby("industry").first().reset_index()
)

sales_stats = (
    sales_food.groupby(["industry", "kind_of_business", "month"])["sales"]
    .agg(avg_sales="mean", lowest_sales="min", highest_sales="max")
    .reset_index().round(2)
)

In [27]:
print("=== BEST MONTHS ===")
print(best_months)

print("\n=== BEST INDUSTRY PER MONTH ===")
print(best_industry_per_month)

print("\n=== BEST BUSINESS PER INDUSTRY ===")
print(best_business_per_industry)

print("\n=== SALES STATS (AVG, MIN, MAX) ===")
print(sales_stats)

=== BEST MONTHS ===
        month        sales
0    December  18978498.48
1      August  17093027.94
2         May  16997337.94
3    November  16962497.25
4        July  16767182.94
5     October  16632662.25
6       March  16620169.17
7        June  16609989.94
8   September  16037848.94
9       April  15966589.17
10    January  14554513.09
11   February  14485459.86

=== BEST INDUSTRY PER MONTH ===
        month    industry      sales
0       April  Automotive  4471542.0
1      August  Automotive  4822818.0
2    December  Automotive  4614576.0
3    February  Automotive  4037466.0
4     January  Automotive  3867979.0
5        July  Automotive  4696992.0
6        June  Automotive  4637376.0
7       March  Automotive  4759220.0
8         May  Automotive  4763342.0
9    November  Automotive  4268662.0
10    October  Automotive  4470684.0
11  September  Automotive  4430278.0

=== BEST BUSINESS PER INDUSTRY ===
                          industry  \
0                       Automotive
1            Fashion & Accessories
2                  Food & Beverage
3                  Fuel & Gasoline
4              General Merchandise
5           Health & Personal Care
6   Home Goods & Building Supplies
7         Home Goods & Electronics
8                    Miscellaneous
9          Office Supplies & Gifts
10              Restaurants & Bars
11             Sports & Recreation

                                     kind_of_business       sales
0                     Motor vehicle and parts dealers  14531121.0
1                Clothing and clothing access. stores   3302936.0
2                            Food and beverage stores   9451004.0
3                                   Gasoline stations   6811521.0
4                          General merchandise stores   9038491.0
5                     Health and personal care stores   4149035.0
6   Building mat. and garden equip. and supplies d...   4586452.0
7           Electronic shopping and mail-order houses   7351761.0
8                                  Nonstore retailers   8511856.0
9        Office supplies, stationery, and gift stores    405487.0
10                  Food services and drinking places   8635492.0
11  Sporting goods, hobby, musical instrument, and...   1123028.0

=== SALES STATS (AVG, MIN, MAX) ===
                industry                                   kind_of_business  \
0             Automotive         Automobile and other motor vehicle dealers
1             Automotive         Automobile and other motor vehicle dealers
2             Automotive         Automobile and other motor vehicle dealers
3             Automotive         Automobile and other motor vehicle dealers
4             Automotive         Automobile and other motor vehicle dealers
..                   ...                                                ...
691  Sports & Recreation  Sporting goods, hobby, musical instrument, and...
692  Sports & Recreation  Sporting goods, hobby, musical instrument, and...
693  Sports & Recreation  Sporting goods, hobby, musical instrument, and...
694  Sports & Recreation  Sporting goods, hobby, musical instrument, and...
695  Sports & Recreation  Sporting goods, hobby, musical instrument, and...

         month  avg_sales  lowest_sales  highest_sales
0        April   85590.62       57767.0       129053.0
1       August   91817.46       59027.0       124722.0
2     December   87227.23       57998.0       112739.0
3     February   76497.54       46213.0       108112.0
4      January   72903.69       44566.0       104500.0
..         ...        ...           ...            ...
691      March    6784.69        5186.0         9323.0
692        May    6751.92        5885.0         8851.0
693   November    7853.92        6904.0        10277.0
694    October    6598.46        5581.0         8849.0
695  September    6882.54        6021.0         8998.0

[696 rows x 6 columns]

In [28]:
# ============================================
# SAVE ALL TO CSV
# ============================================
industry_share.reset_index().to_csv("industry_share.csv", index=False)
top10.to_csv("top10_businesses.csv", index=False)
monthly_sales.to_csv("sales_by_month.csv", index=False)
category_sales.to_csv("food_retail_automotive.csv", index=False)
heatmap_data.to_csv("heatmap_month_industry.csv")
best_months.to_csv("best_months.csv", index=False)
best_industry_per_month.to_csv("best_industry_per_month.csv", index=False)
best_business_per_industry.to_csv("best_business_per_industry.csv", index=False)
sales_stats.to_csv("sales_stats.csv", index=False)

print("✅ All CSVs saved!")

✅ All CSVs saved!

In [29]:
# ============================================
# KPI CARDS — SAVE TO CSV
# ============================================
kpi_data = {
    "metric": ["Total Sales", "Best Month", "Top Industry", "Average Sales"],
    "value": [f"${total_sales:,.2f}", best_month, top_industry, f"${avg_sales:,.2f}"]
}
kpi_df = pd.DataFrame(kpi_data)
kpi_df.to_csv("kpis.csv", index=False)
print("✅ KPIs saved!")

✅ KPIs saved!

In [30]:
industry_count = {}

for index, row in sales_food.iterrows():
    industry = row["industry"]
    if industry in industry_count:
        industry_count[industry] += 1
    else:
        industry_count[industry] = 1

industry_count_df = pd.DataFrame(
    list(industry_count.items()),
    columns=["industry", "total_records"]
).sort_values("total_records", ascending=False)

print(industry_count_df)
industry_count_df.to_csv("industry_count.csv", index=False)
print("✅ Industry count saved!")

                          industry  total_records
1         Home Goods & Electronics           1560
6            Fashion & Accessories           1248
8              General Merchandise            936
0                       Automotive            936
11              Restaurants & Bars            780
3                  Food & Beverage            780
2   Home Goods & Building Supplies            624
7              Sports & Recreation            624
9                    Miscellaneous            468
10         Office Supplies & Gifts            468
4           Health & Personal Care            312
5                  Fuel & Gasoline            312
✅ Industry count saved!

In [31]:
industry_count_df = pd.DataFrame(
    list(industry_count.items()),
    columns=["industry", "total_records"]
).sort_values("total_records", ascending=False)

# Add as column to sales_food
sales_food = sales_food.merge(industry_count_df, on="industry", how="left")

print(sales_food.head())

   Unnamed: 0    month  year                                naics_Code  \
0           0  January  2022             Motor Vehicle & Parts Dealers
1           1  January  2022  Motor Vehicle & Parts Dealers (Combined)
2           2  January  2022                        Automobile Dealers
3           3  January  2022                           New Car Dealers
4           4  January  2022                          Used Car Dealers

                             kind_of_business    industry     sales  \
0             Motor vehicle and parts dealers  Automotive  113548.0
1  Automobile and other motor vehicle dealers  Automotive  104500.0
2                          Automobile dealers  Automotive   96689.0
3                             New car dealers  Automotive   84442.0
4                            Used car dealers  Automotive   12247.0

     category  total_records
0  Automotive            936
1  Automotive            936
2  Automotive            936
3  Automotive            936
4  Automotive            936

In [33]:
sales_food.head(20)

,Unnamed: 0,month,year,naics_Code,kind_of_business,industry,sales,category,total_records
0,0,January,2022,Motor Vehicle & Parts Dealers,Motor vehicle and parts dealers,Automotive,113548.00,Automotive,936
1,1,January,2022,Motor Vehicle & Parts Dealers (Combined),Automobile and other motor vehicle dealers,Automotive,104500.00,Automotive,936
2,2,January,2022,Automobile Dealers,Automobile dealers,Automotive,96689.00,Automotive,936
3,3,January,2022,New Car Dealers,New car dealers,Automotive,84442.00,Automotive,936
4,4,January,2022,Used Car Dealers,Used car dealers,Automotive,12247.00,Automotive,936
5,5,January,2022,"Auto Parts, Accessories & Tire Stores","Automotive parts, acc., and tire stores",Automotive,9047.00,Automotive,936
6,6,January,2022,Furniture & Electronics Stores (Combined),"Furniture, home furn, electronics, and applian...",Home Goods & Electronics,17141.00,Retail,1560
7,7,January,2022,Furniture & Home Furnishings Stores,Furniture and home furnishings stores,Home Goods & Electronics,10423.00,Retail,1560
8,8,January,2022,Furniture Stores,Furniture stores,Home Goods & Electronics,5549.00,Retail,1560
9,9,January,2022,Home Furnishings Stores,Home furnishings stores,Home Goods & Electronics,21850.77,Retail,1560
10,10,January,2022,Floor Covering Stores,Floor covering stores,Home Goods & Electronics,21850.77,Retail,1560
11,11,January,2022,All Other Home Furnishings Stores,All other home furnishings stores,Home Goods & Electronics,21850.77,Retail,1560
12,12,January,2022,Electronics & Appliance Stores,Electronics and appliance stores,Home Goods & Electronics,6718.00,Retail,1560
13,13,January,2022,Household Appliance Stores,Household appliance stores,Home Goods & Electronics,1547.00,Retail,1560
14,14,January,2022,Electronics Stores,Electronics stores,Home Goods & Electronics,5171.00,Retail,1560
15,15,January,2022,Building Material & Garden Supply Stores,Building mat. and garden equip. and supplies d...,Home Goods & Building Supplies,33771.00,Retail,624
16,16,January,2022,Building Material & Supplies Dealers,Building mat. and supplies dealers,Home Goods & Building Supplies,29770.00,Retail,624
17,17,January,2022,Paint & Wallpaper Stores,Paint and wallpaper stores,Home Goods & Building Supplies,1051.00,Retail,624
18,18,January,2022,Hardware Stores,Hardware stores,Home Goods & Building Supplies,2728.00,Retail,624
19,19,January,2022,Food & Beverage Stores,Food and beverage stores,Food & Beverage,74984.00,Food,780

In [35]:
sales_food.head(20)

,Unnamed: 0,month,year,naics_Code,kind_of_business,industry,sales,category,total_records
0,0,January,2022,Motor Vehicle & Parts Dealers,Motor vehicle and parts dealers,Automotive,113548.00,Automotive,936
1,1,January,2022,Motor Vehicle & Parts Dealers (Combined),Automobile and other motor vehicle dealers,Automotive,104500.00,Automotive,936
2,2,January,2022,Automobile Dealers,Automobile dealers,Automotive,96689.00,Automotive,936
3,3,January,2022,New Car Dealers,New car dealers,Automotive,84442.00,Automotive,936
4,4,January,2022,Used Car Dealers,Used car dealers,Automotive,12247.00,Automotive,936
5,5,January,2022,"Auto Parts, Accessories & Tire Stores","Automotive parts, acc., and tire stores",Automotive,9047.00,Automotive,936
6,6,January,2022,Furniture & Electronics Stores (Combined),"Furniture, home furn, electronics, and applian...",Home Goods & Electronics,17141.00,Retail,1560
7,7,January,2022,Furniture & Home Furnishings Stores,Furniture and home furnishings stores,Home Goods & Electronics,10423.00,Retail,1560
8,8,January,2022,Furniture Stores,Furniture stores,Home Goods & Electronics,5549.00,Retail,1560
9,9,January,2022,Home Furnishings Stores,Home furnishings stores,Home Goods & Electronics,21850.77,Retail,1560
10,10,January,2022,Floor Covering Stores,Floor covering stores,Home Goods & Electronics,21850.77,Retail,1560
11,11,January,2022,All Other Home Furnishings Stores,All other home furnishings stores,Home Goods & Electronics,21850.77,Retail,1560
12,12,January,2022,Electronics & Appliance Stores,Electronics and appliance stores,Home Goods & Electronics,6718.00,Retail,1560
13,13,January,2022,Household Appliance Stores,Household appliance stores,Home Goods & Electronics,1547.00,Retail,1560
14,14,January,2022,Electronics Stores,Electronics stores,Home Goods & Electronics,5171.00,Retail,1560
15,15,January,2022,Building Material & Garden Supply Stores,Building mat. and garden equip. and supplies d...,Home Goods & Building Supplies,33771.00,Retail,624
16,16,January,2022,Building Material & Supplies Dealers,Building mat. and supplies dealers,Home Goods & Building Supplies,29770.00,Retail,624
17,17,January,2022,Paint & Wallpaper Stores,Paint and wallpaper stores,Home Goods & Building Supplies,1051.00,Retail,624
18,18,January,2022,Hardware Stores,Hardware stores,Home Goods & Building Supplies,2728.00,Retail,624
19,19,January,2022,Food & Beverage Stores,Food and beverage stores,Food & Beverage,74984.00,Food,780

In [36]:
sales_food.to_csv("sales_food_final.csv", index=False)
print("✅ Saved!")

✅ Saved!